### ISSUE TITLE
Having problems building demo with new Swift 3

### ISSUE THREAD

**Issue by trostli** [fitpay/fitpay-ios-sdk#107]
Hi there!

I'm trying to wrap my head around the IOS SDK by playing with the demo but having trouble getting it to compile. It seems the SDK itself has been updated to Swift 3 but the demo has not. I've tried setting the "Use Legacy Swift Language Verision" flag to YES in the build settings for the target and project but no luck.

Any tips on how to get it to run?

I'm on the develop branch BTW

Update:

I also tried master branch with no luck either

**Comment by andybfp** [comment]
Hi Daniel,

Sorry you're having trouble and thanks for reaching out. Which demo are you referring to?

- we have the reference app in another repo
- there may be some demo/tool apps in the SDK repo that haven't been supported (sorry we forgot to clean this up in the repo but thanks for the reminder!)

FWIW, it's easier for us to support you on these via email. Can you continue the conversation via your contact?

Thanks!

**Comment by trostli** [comment]
I’ve had success running the demo app in the Pagare_iOS_WV repo but cannot get past the login screen since I don’t have a Pebble device. I know in the README there it says -

"It can also be used without a Watch and SmartStrap by setting the app to use a "Mock Device." At application launch, the gear icon can be used to access the setting for "Use Mock Device.”” 

- however I do not see a gear icon anywhere.

The demo app I’m referring to in the fitpay-ios-sdk repo is the FitPaySDKDemo target.

What’s the best for me to learn how to use the iOS SDK? 

And yes please feel free to email me at daniel.trostli@gmail.com

Thanks very much for your help :)

**Comment by andybfp** [comment]
Emailing you.
