### ISSUE TITLE
Swift 3 support for demo?

### ISSUE THREAD

**Issue by sdondon** [fitpay/fitpay-ios-sdk#148]
Hi, I'm trying to integrate your sdk into my app but I don't have any of fitpay enabled device yet. 
So currently I'm testing out with `MockPaymentDeviceConnector`, but I'm having a hard time how this sdk works. I think it will be helpful if your demo support swift 3. Do you guys have any plan for swift 3 support on demo? Your demo was updated like a year ago, and it seems like a great amount of your codes were refactored since then.

**Comment by andybfp** [comment]
Our demo is at https://github.com/fitpay/Pagare_iOS_WV and the demo in this repo is outdated, unsupported, and we should remove it. If you're missing access please reach out to your support contact(s) so we can get you on the integration path and setup.
