### ISSUE TITLE
Adding new verification methods

### ISSUE THREAD

**Issue by lyeskin** [fitpay/fitpay-ios-sdk#243]
Hi guys

We were asked to process two another verification methods, but I can't find mappings for them in the latest SDK version.

Could you please add these two ASAP?
```
//VerfiicationMethodType.swift
case cardholderToCallForAutomatedOTPCode = "CARDHOLDER_TO_CALL_FOR_AUTOMATED_OTP_CODE"
case agentToCallCardholderNumber = "AGENT_TO_CALL_CARDHOLDER_NUMBER"
```

**Comment by jeremiahthomasharris** [comment]
We have merged this into develop and improved comments.
